airflow_dag_repo:
  username: ramadhanputraaf
  endpoint: gitlab.com/ramadhanputraaf/my-stage.git
  branch: stage-release

path_cfg:
  dag_master_directory: /users/firdaramadhanputra/Documents/lab/master_folder
  pl_master_filename: pl_cross_dag.py
  repo_dir: /Users/firdaramadhanputra/Documents/lab/repo
  repo_pl_dir: /Users/firdaramadhanputra/Documents/lab/repo/presentations